### ISSUE TITLE
kubedb operator panics when db-secret is not pre-defined while restoring snapshot

### ISSUE THREAD

**Issue by the-redback** [k8sdb/operator#123]
This example gives panic to kubedb operator. 
https://github.com/k8sdb/cli/blob/master/docs/tutorials/postgres.md#restore-from-snapshot

The operator unable to use db-secret dynamically in this case.
It needs to pre-defined the secret. 

This is an working example. and line 15& 16 is additionally added.
```yaml
apiVersion: kubedb.com/v1alpha1
kind: MySQL
metadata:
  name: r2
  namespace: demo
spec:
  version: 8.0
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
  databaseSecret: 
    secretName: m1-admin-auth
  init:
    snapshotSource:
      name: m1-xyz
```

Operator works fine when this part is defined,
    Spec.DatabaseSecret.secretName = m1-admin-auth

The code is referring to a null field when the secretName is not defined in yaml file.
That gives panic.
