### ISSUE TITLE
Resumption of DB using "original DB yaml" doesn't work more than once

### ISSUE THREAD

**Issue by the-redback** [k8sdb/operator#126]
After pausing a database, when I try to resume it using the same yaml file (which contains **Init** part in **Spec**) , It works fine the first time. 
But, when I repeat the same action (pause and resume), it starts to throw the following error:
```
InitSpec mismatches with DormantDatabase annotation
```
This is the sample YAML file I used:
```yaml
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: p1
  namespace: demo
spec:
  version: 9.5
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
  init:
    scriptSource:
      scriptPath: "postgres-init-scripts/run.sh"
      gitRepo:
        repository: "https://github.com/k8sdb/postgres-init-scripts.git"
```
