### ISSUE TITLE
Postgres TPR stays in unknown state

### ISSUE THREAD

**Issue by TamalSaha** [k8sdb/operator#57]
I created a new postgres using:
```
apiVersion: kubedb.com/v1beta1
kind: Postgres
metadata:
  name: cowrypay-qa-db
  namespace: default
spec:
  databaseSecret:
    secretName: cowrypay-qa-db-admin-auth
  storage:
    accessModes:
    - ReadWriteOnce
    class: pd-standard
    resources:
      requests:
        storage: 10Gi
  version: 9.5-db
```

Since the version `9.5-db`, it immediately went into a `Failed` state. I was able to see that from Pharm.

Then I edited the TPR to change version to `9.5`. It was not picked up. Then I deleted the TPR and created a new one. It was not picked up also. Now, it went into `unknown` state. Now, Pharm is also giving me 500 error.

FYI, the underlying StatefulSet existed from before from old `k8sdb.com` group. What is the issue here?
