### ISSUE TITLE
Integrate prometheus monitoring

### ISSUE THREAD

**Issue by tamalsaha** [k8sdb/operator#64]
```
("/namespaces/:ns/postgreses/:name", handler)
("/namespaces/:ns/<>/:name", handler)

spec:
  monitoring:
    prometheus:
      serviceMonitorSelector:
        matchLabels:
          team: frontend


apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  name: kubedb-<db-ns><db-name>
  labels:
    team: <db.Spec.monitor.Prometheus.labels>
spec:
  selector:
    matchLabels:
      app: <exporter-svc>
  namespaceSelector:
    matchNames:
    - <db-namespace>
  endpoints:
  - port: <exporter-port-name>
    path: '/k8sdb.com/v1beta1/namespaces/:%s/:%s/:%s/metrics'
    interval: 15s
```
![k8sdb-prom-integration](https://cloud.githubusercontent.com/assets/94814/26272251/9e18e890-3cc8-11e7-9982-6af060ead7f4.png)
